### ISSUE TITLE
v4 to v5 Update Functionality Differences

### ISSUE THREAD

**Issue by shellscape** [sindresorhus/get-port#34]
I may need some guidance as to how to go about nailing down the cause. I'm using `getPort` in an `ava` test environment in conjunction with `puppeteer` and `webpack`. When using get-port@4.2.0 everything works as expected. After updating to v5, I get multiple test files attempting to use the same port. My only shot-in-the-dark is that it's somehow related to the changes in v5 to the available port code.

Fwiw, my calls to `getPort` are relatively simple: `getPort({ port: 55555 });`

**Comment by sindresorhus** [comment]
// @stroncium

**Comment by stroncium** [comment]
By design this library doesn't guarantee that it won't give the same result to parallel calls.
> There is a very tiny chance of a race condition if another service starts using the same port number as you in between the time you get the port number and you actually start using it.

- works all the same for another part of the same application, which might find the same port(equals starts using then stops using it) before you start to actually use it.

The change in behavior might be related to switch to async which is supposed to slightly change distribution of code execution between ticks.

However, I can't be entirely sure this is the cause in your case and what is actually happening. Need better reproduction steps.

Also,

**Comment by sindresorhus** [comment]
Duplicate of #23

**Comment by sindresorhus** [comment]
The in-process race condition you're experiencing was fixed by https://github.com/sindresorhus/get-port/commit/73e21d8c2f9ad2d4eb6bff0503292f44014b8bfd.
