### ISSUE TITLE
Cannot find module 'node:net' or its corresponding type declarations.

### ISSUE THREAD

**Issue by DoodahProductions** [sindresorhus/get-port#65]
Hello, I do encounter this issue :

```
node_modules/get-port/index.d.ts:1:29 - error TS2307: Cannot find module 'node:net' or its corresponding type declarations.

1 import {ListenOptions} from 'node:net';

```

Node version : v17.6.0

Thanks for your work on this package.

**Comment by sindresorhus** [comment]
Sounds like you have outdated Node.js types.

**Comment by hakonhagland** [comment]
I have the same problem. I tried to google `node:net` but could not find any information. I tried to reinstall `npm install @types/node` but it did not solve the problem

**Comment by hakonhagland** [comment]
Ok I found that the problem might be that I was using the default setup for writing a VS Code extension. It uses `commonjs` module types by default. If I change the `tsconfig.json` to use compiler option `"module": "es6"` it finds the `node:net` import, however then I ran into [this](https://stackoverflow.com/questions/71927205/how-to-use-get-port-package-from-a-vs-code-extension) issue. Which I now believe cannot be solved since `get-port` is an es module, see the discussion [here](https://github.com/microsoft/vscode/issues/130367). Does anyone know if there a simple way to convert this module to a `commonjs` module so it can be used in a VS Code extension?
